spring:
 application:
  name: start
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@192.168.130.17:1521:XE
  username: KH14_SDK
  password: KH1234

server: 
 port: 80
 
jwt:
 secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==
