spring:
 application: 
  name: demo
 datasource:
  url: jdbc:oracle:thin:@192.168.130.17:1521:XE
  username: KH14_SDK
  password: KH1234
  driver-class-name: oracle.jdbc.driver.OracleDriver 

server:  
 port: 80
